version: '3'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - metadata
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metadata
  metadata:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
  appdata:
    image: postgres:10-alpine
    volumes:
      - "./data/:/host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: metabase
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
  cli:
    build: .
    volumes:
      - "./data/:/host"
